doctrine_migrations:
  #dir_name: "%kernel.project_dir%/src/Migrations"
  # namespace is arbitrary but should be different from App\Migrations
  # as migrations classes should NOT be autoloaded
  #namespace: DoctrineMigrations

  #name: "%kernel.project_dir%/src/Migrations"
  #migrations_namespace: "DoctrineMigrations"
  #executed_at_column_name: "executed_at"
  #migrations_directory: "/data/doctrine/migrations-docs-example/lib/MyProject/Migrations"
  migrations_paths:
    "DoctrineMigrations": "%kernel.project_dir%/src/Migrations"
  all_or_nothing: true
  check_database_platform: true
